// <auto-generated />
using System;
using FluxoCaixa.Lancamentos.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FluxoCaixa.Lancamentos.API.Infrastructure.Data.Migrations;

[DbContext(typeof(LancamentosDbContext))]
partial class LancamentosDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FluxoCaixa.Lancamentos.API.Domain.Entities.Lancamento", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CriadoEm")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("criado_em");

            b.Property<DateTime>("Data")
                .HasColumnType("date")
                .HasColumnName("data");

            b.Property<string>("Descricao")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("descricao");

            b.Property<string>("Tipo")
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnType("character varying(10)")
                .HasColumnName("tipo");

            b.Property<decimal>("Valor")
                .HasColumnType("numeric(15,2)")
                .HasColumnName("valor");

            b.HasKey("Id");

            b.HasIndex("Data").HasDatabaseName("ix_lancamentos_data");
            b.HasIndex("Tipo").HasDatabaseName("ix_lancamentos_tipo");
            b.HasIndex("Data", "Tipo").HasDatabaseName("ix_lancamentos_data_tipo");

            b.ToTable("lancamentos", "public");
        });
#pragma warning restore 612, 618
    }
}
