// <auto-generated />
using System;
using FluxoCaixa.Consolidado.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FluxoCaixa.Consolidado.API.Infrastructure.Data.Migrations;

[DbContext(typeof(ConsolidadoDbContext))]
partial class ConsolidadoDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FluxoCaixa.Consolidado.API.Domain.Entities.ConsolidadoDiario", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("AtualizadoEm")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("atualizado_em");

            b.Property<DateTime>("Data")
                .HasColumnType("date")
                .HasColumnName("data");

            b.Property<int>("QuantidadeLancamentos")
                .HasColumnType("integer")
                .HasColumnName("quantidade_lancamentos");

            b.Property<decimal>("TotalCreditos")
                .HasColumnType("numeric(15,2)")
                .HasColumnName("total_creditos");

            b.Property<decimal>("TotalDebitos")
                .HasColumnType("numeric(15,2)")
                .HasColumnName("total_debitos");

            b.HasKey("Id");

            b.HasIndex("Data")
                .IsUnique()
                .HasDatabaseName("ix_consolidados_data_unique");

            b.ToTable("consolidados_diarios", "public");
        });
#pragma warning restore 612, 618
    }
}
